# Generated by Django 3.2.25 on 2024-09-28 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0002_cardkv'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardinfo',
            name='date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='cardinfo',
            name='time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddConstraint(
            model_name='cardinfo',
            constraint=models.UniqueConstraint(fields=('username', 'address'), name='unique_username_address'),
        ),
    ]
