# Generated by Django 3.2.12 on 2024-06-18 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardInfo',
            fields=[
                ('username', models.CharField(max_length=150)),
                ('bio', models.TextField(blank=True, null=True)),
                ('address', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('link', models.CharField(max_length=255)),
            ],
        ),
    ]
